### ISSUE TITLE
react-native start error: Error watching file for changes: EMFILE

### ISSUE THREAD

**Issue by sunfmin** [sunfmin/notebook#19]
```

This warning is caused by a @providesModule declaration with the same name across two different files.
Loading dependency graph...
Bundling `index.ios.js`
  Analysing...2017-05-14 14:47 node[686] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2017-05-14 14:47 node[686] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2017-05-14 14:47 node[686] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
 ERROR  Error watching file for changes: EMFILE
{"code":"EMFILE","errno":"EMFILE","syscall":"Error watching file for changes:","filename":null}
Error: Error watching file for changes: EMFILE
    at exports._errnoException (util.js:1050:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1374:11)

See http://facebook.github.io/react-native/docs/troubleshooting.html
for common problems and solutions.


```

**Comment by sunfmin** [comment]
```
brew install watchman
```

Solves the problem, don't know why.
